spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BlogBase
    username: test
    password: 1234567890
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    mapper:
      default-view-inclusion: true
blogio:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyrightFrom: "2005"